# Generated by Django 5.1.3 on 2024-12-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
    ]
