# Generated by Django 5.1.3 on 2024-12-22 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_survey_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': [('can_create_survey', 'Can create survey'), ('can_view_survey_results', 'Can view survey results')], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
    ]
