# Generated by Django 5.1.3 on 2024-12-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_survey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': [('can_create_survey', 'Can create survey'), ('can_view_survey_results', 'Can view survey results'), ('can_delete_survey', 'Can delete survey')], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
    ]
