# Generated by Django 5.1.3 on 2024-12-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_pages', '0006_merge_0005_event_0005_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_modify', 'Can modify events')]},
        ),
    ]
