# Generated by Django 5.1.3 on 2024-12-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_pages', '0007_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_modify_event', 'Can modify events')]},
        ),
    ]
